### ISSUE TITLE
关于Angel Representation的一些疑问

### ISSUE THREAD

**Issue by Aikoin** [ideal-idea/SAP#1]
作者您好！我想请教一下您们对应文章中3.5节How to aggregate the views部分的配图**Fig 6**中，维度C和维度V对应的含义是什么？和Fig4中的（V为顶点数，C为每个顶点的空间维数=3）一致吗？如果一致，这里没有代表视图的维度，怎么体现多视图融合的呢？以及公式2中angle stream的Θ代表什么？是根据三元组表示计算出的cos值对应的角度θ的集合吗？
或者Angle Representation部分对应的代码是哪一段呀，看文没理解本想来看代码的，但（因为太菜）没找到对应的代码....
感谢！

**Comment by apenbol** [comment]
1. **C** represents the number of views in fig6, because one views is represented one-dimension angle value after SAP.  But in fig4, The value of **C** is 3 and **C** represents the dimension of an anchor point under the camera coordinates . 
2. $\Theta$ in Equ-2 represents the meaning as you said.  It's an overall description of process.
3. The code of Angle Representation exists on Line 168 in model/SAP.py.

**Comment by Aikoin** [comment]
> 1. **C** represents the number of views in fig6, because one views is represented one-dimension angle value after SAP.  But in fig4, The value of **C** is 3 and **C** represents the dimension of an anchor point under the camera coordinates .
> 2. Θ in Equ-2 represents the meaning as you said.  It's an overall description of process.
> 3. The code of Angle Representation exists on Line 168 in model/SAP.py.

Thank you for your detailed answer, it helps me a lot!!!
Have a nice day! :)
